### ISSUE TITLE
Latest Commits Break Studio At Runtime

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [yamcs/yamcs-studio#106]
Hi there,

It looks like 3a4afd31855f41f6de5eed0006d5cf912553cf6f breaks Studio at runtime. Maven builds the binaries fine, but when attempting to run Studio I get the following errors:

![Screenshot from 2021-04-19 12-38-49](https://user-images.githubusercontent.com/68551873/115279486-6caeb300-a10c-11eb-9535-66d142b4fcab.png)

![Screenshot from 2021-04-19 12-39-45](https://user-images.githubusercontent.com/68551873/115279512-733d2a80-a10c-11eb-9208-859456e2de9b.png)

I looked at the commits and tried fixing it, but couldn't. However, I thought you guys might find this useful:https://stackoverflow.com/a/15223342

EDIT: Here is a dump of system info:

```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

Thanks
Lorenzo

**Comment by fqqb** [comment]
Thanks, should be good now on latest master.
The issue was in the construction of our public p2 repository (Require-Bundle for javax.xml no longer needed)
