### ISSUE TITLE
Display error in Yamcs Studio text update

### ISSUE THREAD

**Issue by nmaas87** [yamcs/yamcs-studio#109]
I found two problems
a) Yamcs Studio Text Update Widget does always show parameters as float, even if they are an integer. The PV-Info does show it correct, but the Text Update Widget not
b) Yamcs Studio Text Update Widget does some weird rounding/display error with floats as shown in the screenshot. This error does not show up in Yamcs Web or the PV Info, but in the Text Update Widget.

![float_error_masked](https://user-images.githubusercontent.com/1331457/123221221-01e47400-d4cf-11eb-8ffa-dffc6a15d3df.png)

Cheers,

Nico

**Comment by fqqb** [comment]
Thanks, both are now fixed on master, for inclusion in next release.
Details:

a) Came from casting int/long to double before printing
b) Came from casting float to double, before printing
