### ISSUE TITLE
"Mark as event" feature removed?

### ISSUE THREAD

**Issue by nmaas87** [yamcs/yamcs-studio#114]
Dear all,
in earlier times it was possible to mark certain timespans in the TM Archive as an event with a name which then could also be quickly found in the webinterface and replayed. I think marking these timespans was only possible via Yamcs Studio. Has this feature been removed right now or is there any other way to get the same feature? (I found it very useful to be directly able to mark certrain timespans for e.g. tests and being able to find and replay them again :))

Thanks a lot!

**Comment by fqqb** [comment]
You are referring to "tags". Yes they are intentionally removed in favour of our timeline feature.
If you have old tags that you still need you can for now still recover them through API: https://docs.yamcs.org/yamcs-http-api/tag/

Some kind of connection between marked timeline events and the studio archive view is not impossible, but not on the shortlist either.

**Comment by nmaas87** [comment]
Ok, thanks for the info!
