### ISSUE TITLE
Yamcs.issueCommand with arguments not working

### ISSUE THREAD

**Issue by PilotWave** [yamcs/yamcs-studio#116]
I am trying to issue commands with arguments in scripts using the Yamcs.issueCommand function and it will not pass the parameters.  I created the simplest command possible receiving a single uint8 parameter to test this further and it still doesn't work.

Yamcs.issueCommand('/FP_CM_MDB/fp_cm_cmd_Noop_Param', {testparam: 2}); 

I tried different syntaxes but I always get the same result.  Same result if I try in the command stack of the display runner.  I can confirm nothing was sent in the command history and I cannot see any error message.  I can get the command to work properly if I send it from the Yamcs web client.

If I pass the same command without arguments it goes through (must have defaults defined).  For example, this will work if testparam has a default value:

Yamcs.issueCommand('/FP_CM_MDB/fp_cm_cmd_Noop_Param()');

**Comment by fqqb** [comment]
Assuming this is the latest version of studio, are you able to upgrade your Yamcs server to latest 5.5.5?
Latest studio uses a newer mechanism to pass command args (and I should have wait a bit before using it in studio).

**Comment by PilotWave** [comment]
I am running from the quickstart repo and it looks like I am up to date with master.  I am not sure what version of the server that is using though.

**Comment by fqqb** [comment]
In your local pom.xml you can verify this line: https://github.com/yamcs/quickstart/blob/master/pom.xml#L19

**Comment by PilotWave** [comment]
yep that works, thanks!
