### ISSUE TITLE
YamcsStudio cannot communicate with Yamcs behind a web server if authentication is used

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs-studio#118]
It seems not currently possible use Yamcs Studeio with a Yamcs deployment behind a web server that performs authentication. YamcsStudio uses the Yamcs client libraries which assume that HTTP form encoding can be used to pass credentials, without web server authentication, to Yamcs, and exchange that for an access token. (See also https://github.com/yamcs/yamcs/issues/653)

We are required to let the web server perform authentication, in a manner prescribed by our network security group. We cannot use token authentication in Yamcs, nor can we let Yamcs perform the authentication itself using form encoding. In order to use YamcsStudio, I think two changes are needed:

1. Modify the Yamcs client libraries to support web server authentication as suggested in https://github.com/yamcs/yamcs/issues/653.
2. Modify YamcsStudio to support selecting basic authentication by the web server rather than passing credentials to Yamcs using form encoding, and allow modification of each HTTP request to include the appropriate authentication header information (again, provided by item 1, above).

**Comment by fqqb** [comment]
Yes, going to look at adding a BASIC option to the connection dialog for likely next version.

**Comment by fqqb** [comment]
On master. A new authentication type "Basic Auth" was added to the Connect dialog (in addition to "Standard" and "Kerberos").
