### ISSUE TITLE
Yamcs Studio (Windows version) Icon is missing

### ISSUE THREAD

**Issue by nmaas87** [yamcs/yamcs-studio#121]
Since around version 1.6.x Yamcs Studio lost its icon and some generic one is shown under Windows (see screenshot)

![icon](https://user-images.githubusercontent.com/1331457/201360149-3950f771-0715-4188-9d5a-1c22e1a7365d.png)

**Comment by fqqb** [comment]
Funny, that's my creation.
Think it's there to stay, until we have a better choice.

The previous icon was using the "Ya" abbreviation, which I've been trying to minimize using.

**Comment by nmaas87** [comment]
Oh, my bad. I thought the Ya Icon was very good - as its also used on the website as favicon - and our OPS and GC personell have been trained on using that. So I guess we will need to manually patch it in the future in our OPS environments. But thanks for your quick answer 👍🏻
