### ISSUE TITLE
Yamcs Studio forgets Workspace

### ISSUE THREAD

**Issue by nmaas87** [yamcs/yamcs-studio#122]
Since around Yamcs Studio 1.6.x version, Yamcs Studio "forgets" its workspace.
If launched, it will start up empty and showcase in the LogMessages thats its workspace is within its mainfolder:
[14:24:41.594] Workspace: /C:/Users/x/Desktop/yamcs-studio-1.6.4-SNAPSHOT/workspace/

If one does chose File -> Switch Workspace it still has the list of the last opened workspace.
Opening the workspace there will bring the program to restart and load the Workspace.
If Yamcs Studio is then closed and opened again, it will again have forgotten its Workspace and one has to click Workspace again to relaunch it within the Workspace.

**Comment by fqqb** [comment]
Fixed on master. There was a tricky issue in the initial workspace selection.

Note you can forcefully override the workspace in the current release by adding the @-data /some/where@ program argument.
