### ISSUE TITLE
Using setPropertyValue on LinkingContainer does not update the opi_file

### ISSUE THREAD

**Issue by philwesthart** [yamcs/yamcs-studio#126]
Using YAMCS Studio 1.7.1, I created a sample page with two buttons and a linking container. Each button runs an embedded Python script to find the linking container using the display.getWidget(<linking_container_name>), and then attempts to set the opi file using setPropertyValue("opi_file", <opi_file_name>). At the end of the script, I write a message to console. On running the OPI file, I see the console message, but linking container otherwise shows no updates. This behavior had been used in our displays previously using v1.5.8. On switching to 1.7.1, the behavior no longer functions.

Sample embedded script shown below.

```
from org.csstudio.opibuilder.scriptUtil import ConsoleUtil

link = display.getWidget("TestLC")
link.setPropertyValue("opi_file","test_page1.opi")
ConsoleUtil.writeInfo("page1 opened in Linking Container")
```

Running on Windows 10 Enterprise, Intel i7

**Comment by fqqb** [comment]
On master, sorry for delay here.
The fix was actually easier than I had anticipated.

Release will come soon, I want to do a few more commits first.
