### ISSUE TITLE
TextUpdate widget displays uint values as signed

### ISSUE THREAD

**Issue by bitblit11** [yamcs/yamcs-studio#27]
The TextUpdate widget displays values incorrectly.  Parameters defined as 32 bit unsigned integers ("uint") are being displayed as 32 bit signed integers ("int").  Request updating this widget to display the signed value as defined by the YAMCS telemetry database.  The versions used were from the git head as of the submission of this issue.

**Comment by bitblit11** [comment]
Just to add to the issue, I'm seeing unexplained inconsistent behavior.  I have two telemetry parameters, both defined as 32 bit unsigned integers.  The TextUpdate widget for the first parameter displays "85897216", but the other widget displays "-85897216".  packet-viewer.sh reports that the first parameter is (little endian) 0x00b01e05, which is correct.  But the other parameter is 0x0050e1fa and should be displayed as 4209070080.

**Comment by fqqb** [comment]
Yamcs Studio shows the engineering value, so there's not to many places where I could see that going wrong. I'm thinking it's a Little Endian Yamcs problem. Can you tell me what raw and engineering values you see with this curl statement?

    curl http://localhost:8090/:instance/api/parameter/:namespace/:name

Replace :namespace and :name with your fully qualified parameter name, and `:instance` with your instance name, for example:

    curl http://localhost:8090/simulator/api/parameter/YSS/SIMULATOR/BatteryVoltage1

**Comment by bitblit11** [comment]
The 0x00b01e05 value shows:
curl http://localhost:8090/windhover/api/parameter/CFS/CFE_TIME/Diag_ToneOverLimit
{"id":{"name":"/CFS/CFE_TIME/Diag_ToneOverLimit"},"rawValue":{"type":2,"uint32Value":85897216},"engValue":{"type":2,"uint32Value":85897216},"acquisitionTime":1446220913597,"generationTime":3537256036031,"acquisitionStatus":0,"processingStatus":true,"acquisitionTimeUTC":"2015-10-30T16:01:17.597","generationTimeUTC":"2082-02-02T11:06:40.031","expirationTime":1446220973597,"expirationTimeUTC":"2015-10-30T16:02:17.597"}

The 0x0050e1fa value shows:

{"id":{"name":"/CFS/CFE_TIME/Diag_ToneUnderLimit"},"rawValue":{"type":2,"uint32Value":-85897216},"engValue":{"type":2,"uint32Value":-85897216},"acquisitionTime":1446220913597,"generationTime":3537256036031,"acquisitionStatus":0,"processingStatus":true,"acquisitionTimeUTC":"2015-10-30T16:01:17.597","generationTimeUTC":"2082-02-02T11:06:40.031","expirationTime":1446220973597,"expirationTimeUTC":"2015-10-30T16:02:17.597"}

**Comment by fqqb** [comment]
right, fixed the interpretation Studio-side. Please have a try with the latest commits (update yamcs too, there was an unrelated change)

Not sure i like the JSON API sending the values as their signed counterparts, but the fix is easy enough.

thanks very much for reporting this particular issue.

**Comment by fqqb** [comment]
Should be fixed on master. Please reopen if this issue still applies.

As for the negative values returned in the JSON API, I reported this is a bug with yamcs' upstream protostuff dependency that does the uint32 serialization, and will maybe implement a workaround in the Yamcs project until their next release comes out, but that's not studio related. So closing this.
