### ISSUE TITLE
Command History: add column filter

### ISSUE THREAD

**Issue by m-sc** [yamcs/yamcs-studio#31]
Sometime the number of value types received by the command history is high and this creates a lot of columns in the view.
The user should be able to quickly filters columns to show only those that are meaningfull for him.

This could be done in the form of a command history "profile" that the user can select.
A "profile" would contain a list of column to be displayed.
The "profiles" would be defined from the preference menu, on command history page.

**Comment by m-sc** [comment]
Still to do: add a preference page to let the user define its own view profiles.

**Comment by fqqb** [comment]
Added an action that allows directly configuring the columns. This is saved to workspace and restored on a next session. (same dialog was added for Event Log btw)

![image](https://user-images.githubusercontent.com/145170/44341336-eb4c8180-a487-11e8-87e8-880297cebae5.png)
