### ISSUE TITLE
Build error on latest master

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs-studio#51]
I'm at:

commit c9efa30b039f1b5d2b571843fb3e2c7972871f60
Author: Fabian Diet <XXXX>
Date:   Thu Mar 15 14:55:20 2018 +0100

    Use Yamcs 4.1.2

And I get the following error when I do a "mvn clean install":

[INFO] Adding repository file:/home/tom/sources/yamcs-studio/bundles/org.yamcs.studio.alarms//../../p2deps/org.yamcs.studio.p2deps.repository/target/repository
[INFO] Resolving dependencies of MavenProject: org.yamcs.studio:org.yamcs.studio.alarms:1.0.0-SNAPSHOT @ /home/tom/sources/yamcs-studio/bundles/org.yamcs.studio.alarms/pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.yamcs.studio.alarms 1.0.0.qualifier
[ERROR]   Missing requirement: org.yamcs.studio.alarms 1.0.0.qualifier requires 'bundle org.yamcs.client 0.0.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.yamcs.studio:org.yamcs.studio.alarms:1.0.0-SNAPSHOT @ /home/tom/sources/yamcs-studio/bundles/org.yamcs.studio.alarms/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/

**Comment by fqqb** [comment]
Look like maven was not run on the p2deps project.
This must be done before the main maven build. It packages the yamcs api (currently v4.1.2) in an OSGI-friendly bundle such that it can be used in Eclipse.

Either run `mvn -f p2deps/pom.xml clean install`

Or run `make` from the main directory which automatically builds both maven reactors in order.

(btw, modified your original message to remove my email address  :wink:)

**Comment by tomvanbraeckel** [comment]
A clear case of RTFM :-) sorry about that, it works now!
