### ISSUE TITLE
Yamcs Studio v1.0.3 cannot connect to Yamcs Server 3.4.3

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs-studio#58]
Yamcs Studio v1.0.3 cannot connect to Yamcs Server 3.4.3
It keeps trying for a few times and then it gives up.

It works fine for the previous version, Yamcs Studio v1.0.2

A tcpdump reveals that both v1.0.2 and v1.0.3 do a "GET /_websocket/fsl-em-dev HTTP/1.1" to which the server replies with a "HTTP/1.1 101 Switching Protocols". But after this, v1.0.2 does a new request and continues establishing the connection, whereas v1.0.3 does nothing at this point...

Packet captures of v1.0.2 and v1.0.3 will be provided through other means as they contain sensitive information and cannot be attached here.

**Comment by fqqb** [comment]
Probably related to use of yamcs-client 4.4.2 in yamcs-studio v1.0.3 (different from 4.4.1 in yamcs-studio v1.0.2).

We will need to repackage with yamcs-client 4.5.0 which includes this fix for old Yamcs instances: https://github.com/yamcs/yamcs/commit/10f84c5a3ad1499a332269d4ab8079c7f3f74dae

**Comment by tomvanbraeckel** [comment]
Thank you for the quick confirmation.

Does this mean v1.0.4 will be released with a fix for this issue? We prefer a new release rather than repackaging the v1.0.3 because we use the version number for configuration control.

**Comment by fqqb** [comment]
i'd like to release a 1.0.4 for this (and the other fix you reported last week), but need to test a bit first against 3.4.x myself. There have been other changes in Yamcs 4.5.0 which make this not so obvious.

**Comment by fqqb** [comment]
Can you try out this snapshot:
https://owncloud.spaceapplications.com/owncloud/index.php/s/jnw2J15BhXTK8pl

It seems working fine now on my v3 test setup.

**Comment by tomvanbraeckel** [comment]
It is still unable to connect:

[12:45:23.889] Yamcs Studio v1.0.4.201807031021
[12:45:23.891] Workspace: /C:/Users/busocgc/testworkspace/
[12:45:41.988] Connecting to http://192.168.127.150:8090/fsl-em-dev
[12:45:42.627] WebSocket exception. Closing channel
[12:45:43.651] WebSocket exception. Closing channel
[12:45:44.665] WebSocket exception. Closing channel
[12:45:45.676] WebSocket exception. Closing channel
[12:45:46.689] WebSocket exception. Closing channel

We are using Yamcs Server v3.4.3 which should be the same as v3.4.4 except for "added the possibility to exclude parameter groups from replays".

It works fine with Yamcs Studio v1.0.2 so the issue does not appear to be on the server-side.

**Comment by tomvanbraeckel** [comment]
It was confirmed that the root cause here is the support to both the client and server for websocket subprotocols. This subprotocol is only added on the new  code path (/_websocket/:instance) and not on the legacy code path (/:instance/_websocket) which Yamcs 3.4.x uses.

Fabian has a temporary fix but will try to improve it a bit more. The fix is to catch the subprotocol failure and trigger the legacy code after this. That means that Yamcs Studio will then (successfully) connect with the old /:instance/_websocket urls.

**Comment by fqqb** [comment]
Can you try with the freshly released v1.0.4?
https://github.com/yamcs/yamcs-studio/releases/tag/v1.0.4

Going forward v1.0.x release target Yamcs v3, whereas v1.1.x releases target the latest Yamcs

**Comment by fqqb** [comment]
Closing. Please reopen or issue new tickets if you think there is still a problem.
