### ISSUE TITLE
Yamcs Studio v1.0.2 OpenDisplay() opens some displays in "Builder" mode

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs-studio#59]
When a Spell procedure opens a Yamcs Studio display with the OpenDisplay() function, it opens some displays always in "Builder" mode, making it impossible to use the display for data entry.

Even when only the "Runner" window is open, this happens. It will open an editor pane inside the "Runner" window, next to the normal "Runner" panes.

This behavior affects only specific displays but we are unable to resolve it.

- We tried doing a "Reset Windows" which makes the editor pane go away but it comes back when we do an OpenDisplay() from Spell again.
- We tried removing the e4.workbench folder from the .metadata/.plugins in the workspace because it contains a reference or 2 to the display that has the issue and restarted Yamcs, but strangely, this also did not resolve it.

We had this issue for another display as well, but that issue went away the next day... very strange...

What could cause this? How can we fix it?

**Comment by fqqb** [comment]
Should be fixed in v1.0.4: https://github.com/yamcs/yamcs-studio/releases/tag/v1.0.4

Displays opened in this manner will open in the Display Runner window. If this window is not yet open, it will open automatically.

**Comment by fqqb** [comment]
Closing. Please reopen or issue new tickets if you think there is still a problem.
