### ISSUE TITLE
Old Yamcs Studio displays incompatible with Yamcs Studio v1.0.2 and later

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs-studio#60]
Yamcs Studio v1.0.2 and later cannot handle the "sw://" prefix of /VAR/ variables.

Yamcs Studio v1.0.0.beta-31 cannot handle /VAR variables without the sw:// prefix.

This incompatibility prevents us from switching between the 2 versions, which is problematic because we want to be able to test the new Yamcs Studio and report issues, without modifying the displays every time we switch from one version to the other...

Would it be possible to do a simple fix in the next Yamcs Studio (v1.0.4?) so that the sw:// prefix is simply ignored without breaking the display functionality? This would give us time to test and migrate to the new version while still having the option of using the old and validated version in case of issues...

**Comment by fqqb** [comment]
Can you try with v1.0.4: https://github.com/yamcs/yamcs-studio/releases/tag/v1.0.4
This should add some support for sw:// again. But be cautious you may have subscribe/unsubscribe issues if you use the same parameter both with sw:// and without in different displays.

**Comment by fqqb** [comment]
Closing. Please reopen or issue new tickets if you think there is still a problem.
