### ISSUE TITLE
controls for sending telecommands

### ISSUE THREAD

**Issue by vinnitu** [yamcs/yamcs-studio#63]
Can you show example sending telecommand with arguments with studio?

**Comment by fqqb** [comment]
To send from a control in an opi file, you can attach an action to a control that executes JavaScript:

    importPackage(Packages.org.yamcs.studio.script);
    Yamcs.issueCommand('/YSS/SIMULATOR/SWITCH_VOLTAGE_ON(voltage_num: 1)');

If your arguments are dynamic, you can read the values of PVs or pop-up an input dialog to the user. A common pattern is to place input controls in the display attached to local PVs (`loc://blabla`) and then read the value of those PVs when the control is actioned.

For more on scripts, you could have a look a the 'OPI Examples' project available via `File > New > Example ...`.

Alternatively, you can graphically prepare a stack of commands via the 'Command Stack' view and then send them from there.

Regardless of how you send commands, the status can be followed via the 'Command History' view.

**Comment by vinnitu** [comment]
can you share simple OPI example with radio button when on switch send command with index (or something from property) as argument?

**Comment by fqqb** [comment]
Closing because old, but if somebody still lands here: previous comment seems reasonably complete.

Further the online documentation was recently updated to include a reference of available script API: https://docs.yamcs.org/yamcs-studio/scripts/api/

Many example usages in 'OPI Examples' project.
