### ISSUE TITLE
grafana datasource

### ISSUE THREAD

**Issue by vinnitu** [yamcs/yamcs-studio#64]
Hi, again! )

Can we connect yamcs rocksdb as datasource for grafana?

As I see in readme https://github.com/percona/grafana-dashboards prometheus has MongoDB RocksDB as storage engine

**Comment by xpromache** [comment]
Currently it is not possible. 
One would need to add a new Grafana data source implementation using Yamcs API (https://www.yamcs.org/docs/http/General/) 

The structure of the data stored by Yamcs in rocksdb is specific to yamcs and should be accessed using the Yamcs API. Some data like binary telemetry packets can probably not be shown in an appropriate way in Grafana. Same for commands or command history. 

But for simple parameter data it should be doable.
