### ISSUE TITLE
Connecting to a different instance while already connected fails half of the time

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs-studio#65]
When Yamcs Studio (v1.0.4) is connected to a certain instance of Yamcs Server (v3.4.7) and the user does "Yamcs" - "Connect..." without disconnecting first, the connection seems to fail in around 50% of the cases.

The failure brings Yamcs Studio to a weird state: in the bottom bar, it says "Offline" and the "Yamcs" - "Disconnect" menu entry is grayed out, as if it's not connected.  But in the "Data Links", the data links are active (counters increasing) but they show the data links of the previous instance, not the newly connected one:

![conflicting_connection_info](https://user-images.githubusercontent.com/3263433/48553095-e3f81100-e8da-11e8-90e9-253415dba03c.png)

To workaround this issue, the user needs to do an explicit "Disconnect" before doing a "Connect". This is sometimes a bit difficult because in the faulty state, the "Disconnect" menu entry is grayed out, even though the connection status is "Offline". So the user needs to first connect to the previous, working instance, then disconnect, and then connect to the new instance.

Solutions:
- Ideally, "Connect..." should always work, regardless of whether Yamcs Studio is already connected. Connect (while already connected) or "first Disconnect, then Connect" should be equivalent.
- Alternatively, "Connect" should be grayed out while already connected, so that the user is forced to "Disconnect" first and doesn't end up in this weird state.

**Comment by fqqb** [comment]
Going to close because connectivity has been rewritten multiple times since v1.0.4, including in the v1.5.0 release out Today. This also fixes an issue with "Offline" being shown when it was actually "Online".

Your solutions about "Connect ..." doing a disconnect first, is how it should work indeed. If not, there's a bug.
