### ISSUE TITLE
YAMCS-STUDIO command stacks with same commands containing different arguments

### ISSUE THREAD

**Issue by gabrieleconti** [yamcs/yamcs-studio#66]
Creating a command stack in Yamcs studio is impossible if the command stack contains twice or more time the same command, but with different arguments. 
For example, suppose we want to create a command stack containing the commands CMD(0) and CMD(1) to be executed in this order, where 0 and 1 are two different arguments. Once we select the argument of the second command, the argument of the first command changes as well. In this example, the final result of the command stack is going to be CMD(1) and CMD(1), which is of course different from the wished result.

**Comment by fqqb** [comment]
This seems to happen only when using the copy/paste options from the right-click menu. I'm preparing a fix. A workaround is to add commands via the 'add' button then they are really distinct.

**Comment by fqqb** [comment]
Closing. Fixed for your next release
