### ISSUE TITLE
opi vs Qt ui

### ISSUE THREAD

**Issue by vinnitu** [yamcs/yamcs-studio#74]
I trying make autogenerated opi files with predefined xml-templates and want to tell that opi format has drawbacks compared to Qt ui (for example) and it is not simple to do it... Do you have any plans to impove this format?

**Comment by fqqb** [comment]
The OPI displays are originally developed by CS-Studio people. We forked their code in order to allow for deeper integration with our own source code. This gives us the possibility to change it as needed, but it's not something we have needed to do so far, as it fits our use cases quite well.

**Comment by vinnitu** [comment]
I see
