### ISSUE TITLE
user defined type in xls config

### ISSUE THREAD

**Issue by Vitaliy136** [yamcs/yamcs-studio#75]
landing.xls has position type

position = { 
  float32 longitude;
  float32 latitude;
  float32 altitude
}

What name should I set in PV name property if using xygraph widget for plotting.
I tried setting (/YSS/SIMULATOR/Position.longitude) but this did not work.

**Comment by vinnitu** [comment]
It is interesting thing, when do you plan add support to web and studio?

**Comment by xpromache** [comment]
When time allows....

We appreciate help, though!

**Comment by fqqb** [comment]
With the latest release of studio and server it is now possible to add aggregate members (and array entries) to displays.
