### ISSUE TITLE
Yamcs Studio v1.0.5: Connection cannot be established to server when "Save password" is disabled

### ISSUE THREAD

**Issue by alejandiaz** [yamcs/yamcs-studio#81]
Yamcs Studio v1.0.5 trying to connect to Yamcs-server v3.4.9 is unsuccessful displaying the following message:

Connection to http://XXX.XXX.XXX.XXX:XXXX failed (attempt X of X)

We have been able to identify and reproduce this bug:
-Open the Yamcs-Studio : Yamcs Server Connections window.
-Connect to a server with the "Save Password" option disabled.
-Connection fails.

This is not blocking issue. Once you enable the "Save Password" option the connection can be established with success.

**Comment by fqqb** [comment]
This was recently discovered and fixed in the latest release branch too. I'll see about backporting this for the next 1.0.x release.

**Comment by fqqb** [comment]
Fixed on 3.4.x branch, shall be included in next release.
