### ISSUE TITLE
How to show archived parameter data on XYGraph widget?

### ISSUE THREAD

**Issue by AdamElliott-AB** [yamcs/yamcs-studio#89]
Can you view past parameter data using a XYGraph widget? I saw this comment from a while ago which sounds like the answer was no at the time https://github.com/yamcs/yamcs-studio/issues/72#issuecomment-453494619

I'm hoping this is possible now as this is a pretty important feature.

**Comment by fqqb** [comment]
Sorry you can't. The comment from then is still accurate. The closest you can get to it, is by starting a replay with a display open. 

We typically use Yamcs Studio for realtime monitoring, and for archive access combine it with the web interface, which does have capability for combining archive with realtime at parameter-level.

Yamcs Studio is an adaptation of CS-Studio which does have a feature called Data Browser, which you can find more info about in this article: https://accelconf.web.cern.ch/pc08/papers/tup009.pdf

I think it may be possible to include and adapt that somehow in the Yamcs Studio product, as a more feasible alternative to that shared timeline idea from the linked issue. But it's not something that's on our agenda.

**Comment by AdamElliott-AB** [comment]
Okay, understood. Thanks.
