### ISSUE TITLE
Archive view in yamcs studio is not working? Need some assistance 

### ISSUE THREAD

**Issue by AdityaKumarBej** [yamcs/yamcs-studio#95]
The studio is connected and all telecommands and telemetry is loaded successfully. I am able to issue commands, view command history, see event log but not able to work with archive view. Upon clicking it, it just stays blank.

**Comment by fqqb** [comment]
Indeed, I was hit by it too just Yesterday, and it's the final thing preventing from publishing the next release (although it must have happened it the last few releases too).

The issue appears to be related to the use of an embedded JRE and so far I've seen it only happen on Linux. You can workaround it by updating the path of the -vm flag in the Yamcs Studio.ini to an external (compatible) JVM.

The root error can be found in the .metadata/.log of the workspace, it's related to the SWT/AWT bridging that is particular to this component.

Thanks for reporting

**Comment by AdityaKumarBej** [comment]
Thanks for the response!

I have modified by yamcs studio.ini file 

-startup
plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.1100.v20190907-0426
-vm
/home/system3/jdk-15/jre1.8.0_271/bin/
-vmargs
-Xmx2048m
-Declipse.p2.unsignedPolicy=allow
-Duser.timezone=GMT
-Dosgi.requiredJavaVersion=1.8
-Dorg.eclipse.update.reconcile=false
--add-modules=ALL-SYSTEM

But i get an error (image attached) when i launch yamcs studio post saving the update changes to the ini file.
![image](https://user-images.githubusercontent.com/57063297/100327634-8df1f400-2ff1-11eb-83b0-c6ca509b99b3.png)

**Comment by fqqb** [comment]
i think the error must be further down in that message. Maybe try a JDK if you have one (no JRE)
I'll investigate the root issue asap though, but Today stuck in meetings.

**Comment by fqqb** [comment]
Should be solved in Today's release:
https://github.com/yamcs/yamcs-studio/releases/tag/v1.5.3

The issue seemed to be some incompatibility between JRE14 and SWT. Release v1.5.3 bundles a JRE11, which appears to work fine.

We'll move back to a JRE14 only after the Archive view is rewritten to draw on a plain SWT canvas (which is something I've been postponing for a while now).

**Comment by AdityaKumarBej** [comment]
Thank you Fabian!
